#!/bin/sh

function listworkspaces {
  atleast=6
  ws=($(hyprctl -j workspaces | jq '.[].id' | sort))
  current=${1:-$(hyprctl -j activewindow | jq '.workspace.id')}
  max=$(( ${ws[-1]} > $atleast ? ${ws[-1]} : $atleast))

  printf '(box :class "works" :orientation "v" :halign "center" :valign "start" :space-evenly false :spacing "-5" '
  for w in $(seq $max); do
    [[ $w == $current ]] && dot="" || dot=""
    if [[ $w == $current ]]; then
      class="focused"
    else
      if printf '%s\0' "${ws[@]}" | grep -Fxqz -- $w; then
        class="unfocused"
      else
        class="empty"
      fi
    fi

    printf '(button :class "%s" :onclick "hyprctl dispatch workspace %s" "%s")' $class $w $dot
  done
  echo -e ')'
}

function workspaces
{
  case ${1%>>*} in
    "workspace")
      current=${1#*>>}
      listworkspaces $current
      ;;
    *)
      ;;
  esac
}

listworkspaces
socat -U - UNIX-CONNECT:/tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/.socket2.sock | while read line; do workspaces $line; done
